# Generated by Django 3.2.8 on 2021-12-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Clothe',
        ),
    ]
