# Generated by Django 3.2.8 on 2021-12-18 09:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_clothes_clothe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Baby'), ('T', 'Traditional'), ('Mod', 'Modern'), ('C', 'Classic')], default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='gender_spec',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Baby'), ('T', 'Traditional'), ('Mod', 'Modern'), ('C', 'Classic')], default='M', max_length=6),
        ),
    ]
