# Generated by Django 3.2.8 on 2021-12-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211218_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='size',
        ),
    ]
