# Generated by Django 3.2.8 on 2022-01-01 02:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_clothe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='background_image',
            field=models.ImageField(default='Laiyoweb\\main\\static\\main\\images\\paper-g0b57e8602_1920.jpg', upload_to='', verbose_name=main.models.tailor_background_path),
        ),
        migrations.AddField(
            model_name='tailor',
            name='profile_image',
            field=models.ImageField(default='Laiyoweb\\main\\static\\main\\images\x08lank-profile-picture-gc048af202_1280.png', upload_to=main.models.tailor_profile_path),
        ),
    ]
