# Generated by Django 3.2.8 on 2022-01-01 03:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220101_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='background_image',
            field=models.ImageField(default='Laiyoweb\\main\\static\\main\\images\\paper-g0b57e8602_1920.jpg', upload_to=main.models.tailor_background_path),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='profile_image',
            field=models.ImageField(default='Tailor_12/profile_image/images/blank-profile-picture-gc048af202_1280.png', upload_to=main.models.tailor_profile_path),
        ),
    ]
